package commands

const (
	// Connection / Server
	CMD_PING     = "PING"
	CMD_ECHO     = "ECHO"
	CMD_QUIT     = "QUIT"
	CMD_AUTH     = "AUTH"
	CMD_SELECT   = "SELECT"
	CMD_FLUSHDB  = "FLUSHDB"
	CMD_FLUSHALL = "FLUSHALL"
	CMD_INFO     = "INFO"
	CMD_CLIENT   = "CLIENT"
	CMD_SHUTDOWN = "SHUTDOWN"
	CMD_CONFIG   = "CONFIG"
	CMD_COMMAND  = "COMMAND"
	CMD_ROLE     = "ROLE"
	CMD_MONITOR  = "MONITOR"
	CMD_TIME     = "TIME"
	CMD_DEBUG    = "DEBUG"
	CMD_SLOWLOG  = "SLOWLOG"
	CMD_LATENCY  = "LATENCY"
	CMD_STATS    = "STATS"

	// Key operations
	CMD_DEL       = "DEL"
	CMD_DUMP      = "DUMP"
	CMD_EXISTS    = "EXISTS"
	CMD_EXPIRE    = "EXPIRE"
	CMD_PEXPIRE   = "PEXPIRE"
	CMD_EXPIREAT  = "EXPIREAT"
	CMD_PEXPIREAT = "PEXPIREAT"
	CMD_TTL       = "TTL"
	CMD_PTTL      = "PTTL"
	CMD_PERSIST   = "PERSIST"
	CMD_RENAME    = "RENAME"
	CMD_RENAMENX  = "RENAMENX"
	CMD_TYPE      = "TYPE"
	CMD_KEYS      = "KEYS"
	CMD_SCAN      = "SCAN"
	CMD_SORT      = "SORT"
	CMD_RANDOMKEY = "RANDOMKEY"
	CMD_RESTORE   = "RESTORE"
	CMD_MIGRATE   = "MIGRATE"

	// String commands
	CMD_SET      = "SET"
	CMD_GET      = "GET"
	CMD_SETNX    = "SETNX"
	CMD_SETEX    = "SETEX"
	CMD_SETRANGE = "SETRANGE"
	CMD_GETRANGE = "GETRANGE"
	CMD_GETSET   = "GETSET"
	CMD_INCR     = "INCR"
	CMD_DECR     = "DECR"
	CMD_INCRBY   = "INCRBY"
	CMD_DECRBY   = "DECRBY"
	CMD_APPEND   = "APPEND"
	CMD_STRLEN   = "STRLEN"
	CMD_BITCOUNT = "BITCOUNT"
	CMD_BITOP    = "BITOP"
	CMD_BITPOS   = "BITPOS"
	CMD_SETBIT   = "SETBIT"
	CMD_GETBIT   = "GETBIT"

	// Hash commands
	CMD_HSET    = "HSET"
	CMD_HGET    = "HGET"
	CMD_HDEL    = "HDEL"
	CMD_HLEN    = "HLEN"
	CMD_HKEYS   = "HKEYS"
	CMD_HVALS   = "HVALS"
	CMD_HGETALL = "HGETALL"
	CMD_HMSET   = "HMSET"
	CMD_HMGET   = "HMGET"
	CMD_HINCRBY = "HINCRBY"
	CMD_HEXISTS = "HEXISTS"
	CMD_HSCAN   = "HSCAN"
	CMD_HSETNX  = "HSETNX"
	CMD_HSTRLEN = "HSTRLEN"

	// List commands
	CMD_LPUSH      = "LPUSH"
	CMD_RPUSH      = "RPUSH"
	CMD_LPOP       = "LPOP"
	CMD_RPOP       = "RPOP"
	CMD_LINDEX     = "LINDEX"
	CMD_LSET       = "LSET"
	CMD_LREM       = "LREM"
	CMD_LLEN       = "LLEN"
	CMD_LRANGE     = "LRANGE"
	CMD_LTRIM      = "LTRIM"
	CMD_BLPOP      = "BLPOP"
	CMD_BRPOP      = "BRPOP"
	CMD_BRPOPLPUSH = "BRPOPLPUSH"
	CMD_RPOPLPUSH  = "RPOPLPUSH"
	CMD_LINSERT    = "LINSERT"
	CMD_LMOVE      = "LMOVE"
	CMD_LMPOP      = "LMPOP"

	// Set commands
	CMD_SADD        = "SADD"
	CMD_SREM        = "SREM"
	CMD_SPOP        = "SPOP"
	CMD_SMOVE       = "SMOVE"
	CMD_SISMEMBER   = "SISMEMBER"
	CMD_SCARD       = "SCARD"
	CMD_SINTER      = "SINTER"
	CMD_SINTERSTORE = "SINTERSTORE"
	CMD_SUNION      = "SUNION"
	CMD_SUNIONSTORE = "SUNIONSTORE"
	CMD_SDIFF       = "SDIFF"
	CMD_SDIFFSTORE  = "SDIFFSTORE"
	CMD_SSCAN       = "SSCAN"
	CMD_SRANDMEMBER = "SRANDMEMBER"
	CMD_SINTERCARD  = "SINTERCARD"

	// Sorted Set (ZSet) commands
	CMD_ZADD             = "ZADD"
	CMD_ZREM             = "ZREM"
	CMD_ZINCRBY          = "ZINCRBY"
	CMD_ZCARD            = "ZCARD"
	CMD_ZSCORE           = "ZSCORE"
	CMD_ZRANK            = "ZRANK"
	CMD_ZREVRANK         = "ZREVRANK"
	CMD_ZRANGE           = "ZRANGE"
	CMD_ZRANGEBYSCORE    = "ZRANGEBYSCORE"
	CMD_ZREVRANGE        = "ZREVRANGE"
	CMD_ZREVRANGEBYSCORE = "ZREVRANGEBYSCORE"
	CMD_ZRANGEBYLEX      = "ZRANGEBYLEX"
	CMD_ZREVRANGEBYLEX   = "ZREVRANGEBYLEX"
	CMD_ZINTERSTORE      = "ZINTERSTORE"
	CMD_ZUNIONSTORE      = "ZUNIONSTORE"
	CMD_ZSCAN            = "ZSCAN"

	// Pub/Sub commands
	CMD_PUBLISH      = "PUBLISH"
	CMD_SUBSCRIBE    = "SUBSCRIBE"
	CMD_UNSUBSCRIBE  = "UNSUBSCRIBE"
	CMD_PSUBSCRIBE   = "PSUBSCRIBE"
	CMD_PUNSUBSCRIBE = "PUNSUBSCRIBE"
	CMD_PUBSUB       = "PUBSUB"

	// Transaction / scripting
	CMD_MULTI   = "MULTI"
	CMD_EXEC    = "EXEC"
	CMD_DISCARD = "DISCARD"
	CMD_WATCH   = "WATCH"
	CMD_UNWATCH = "UNWATCH"
	CMD_EVAL    = "EVAL"
	CMD_EVALSHA = "EVALSHA"
	CMD_SCRIPT  = "SCRIPT"
	CMD_LUA     = "LUA"

	// Geo commands
	CMD_GEOADD            = "GEOADD"
	CMD_GEODIST           = "GEODIST"
	CMD_GEOHASH           = "GEOHASH"
	CMD_GEOPOS            = "GEOPOS"
	CMD_GEORADIUS         = "GEORADIUS"
	CMD_GEORADIUSBYMEMBER = "GEORADIUSBYMEMBER"
	CMD_GEORADIUSBYLEX    = "GEORADIUSBYLEX"
	CMD_GEOSEARCH         = "GEOSEARCH"
	CMD_GEOSEARCHSTORE    = "GEOSEARCHSTORE"

	// HyperLogLog
	CMD_PFADD   = "PFADD"
	CMD_PFCOUNT = "PFCOUNT"
	CMD_PFMERGE = "PFMERGE"

	// Streams
	CMD_XADD       = "XADD"
	CMD_XDEL       = "XDEL"
	CMD_XTRIM      = "XTRIM"
	CMD_XCLAIM     = "XCLAIM"
	CMD_XAUTOCLAIM = "XAUTOCLAIM"
	CMD_XGROUP     = "XGROUP"
	CMD_XINFO      = "XINFO"
	CMD_XREAD      = "XREAD"
	CMD_XREADGROUP = "XREADGROUP"
	CMD_XACK       = "XACK"
	CMD_XPENDING   = "XPENDING"
	CMD_XRANGE     = "XRANGE"
	CMD_XREVRANGE  = "XREVRANGE"
	CMD_XSETID     = "XSETID"
	CMD_XCAP       = "APOP" // or XPOP in newer versions
	CMD_XPOP       = "XPOP" // newer

	// Bitmaps / BIT commands
	CMD_BITFIELD_RO = "BITFIELD_RO"
	CMD_BITFIELD    = "BITFIELD"

	// other commands
	CMD_STRALGO   = "STRALGO"
	CMD_SWAPDB    = "SWAPDB"
	CMD_UNLINK    = "UNLINK"
	CMD_WAIT      = "WAIT"
	CMD_REPLICAOF = "REPLICAOF"
	CMD_REPLICA   = "REPLICA"
	CMD_PSYNC     = "PSYNC"
	CMD_LUA_RO    = "LUA_RO"
	CMD_LUA_WRITE = "LUA_WRITE"
	CMD_HELLO     = "HELLO"
)

var AllCommands = []string{
	CMD_PING, CMD_ECHO, CMD_QUIT, CMD_AUTH, CMD_SELECT, CMD_FLUSHDB, CMD_FLUSHALL, CMD_INFO, CMD_CLIENT, CMD_SHUTDOWN, CMD_CONFIG,
	CMD_COMMAND, CMD_ROLE, CMD_MONITOR, CMD_TIME, CMD_DEBUG, CMD_SLOWLOG, CMD_LATENCY, CMD_STATS, CMD_PSUBSCRIBE, CMD_SUBSCRIBE,
	CMD_UNSUBSCRIBE, CMD_PUBSUB,
	CMD_DEL, CMD_DUMP, CMD_EXISTS, CMD_EXPIRE, CMD_PEXPIRE, CMD_EXPIREAT, CMD_PEXPIREAT, CMD_TTL, CMD_PTTL, CMD_PERSIST,
	CMD_RENAME, CMD_RENAMENX, CMD_TYPE, CMD_KEYS, CMD_SCAN, CMD_SORT, CMD_RANDOMKEY, CMD_RESTORE, CMD_MIGRATE,
	CMD_SET, CMD_GET, CMD_SETNX, CMD_SETEX, CMD_SETRANGE, CMD_GETRANGE, CMD_GETSET, CMD_INCR, CMD_DECR, CMD_INCRBY,
	CMD_DECRBY, CMD_APPEND, CMD_STRLEN, CMD_BITCOUNT, CMD_BITOP, CMD_BITPOS, CMD_SETBIT, CMD_GETBIT, CMD_BITFIELD,
	CMD_HSET, CMD_HGET, CMD_HDEL, CMD_HLEN, CMD_HKEYS, CMD_HVALS, CMD_HGETALL, CMD_HMSET, CMD_HMGET, CMD_HINCRBY,
	CMD_HEXISTS, CMD_HSCAN, CMD_HSETNX, CMD_HSTRLEN,
	CMD_LPUSH, CMD_RPUSH, CMD_LPOP, CMD_RPOP, CMD_LINDEX, CMD_LSET, CMD_LREM, CMD_LLEN, CMD_LRANGE, CMD_LTRIM,
	CMD_BLPOP, CMD_BRPOP, CMD_BRPOPLPUSH, CMD_RPOPLPUSH, CMD_LINSERT, CMD_LMOVE, CMD_LMPOP,
	CMD_SADD, CMD_SREM, CMD_SPOP, CMD_SMOVE, CMD_SISMEMBER, CMD_SCARD, CMD_SINTER, CMD_SINTERSTORE,
	CMD_SUNION, CMD_SUNIONSTORE, CMD_SDIFF, CMD_SDIFFSTORE, CMD_SSCAN, CMD_SRANDMEMBER, CMD_SINTERCARD,
	CMD_ZADD, CMD_ZREM, CMD_ZINCRBY, CMD_ZCARD, CMD_ZSCORE, CMD_ZRANK, CMD_ZREVRANK, CMD_ZRANGE,
	CMD_ZRANGEBYSCORE, CMD_ZREVRANGE, CMD_ZREVRANGEBYSCORE, CMD_ZRANGEBYLEX, CMD_ZREVRANGEBYLEX,
	CMD_ZINTERSTORE, CMD_ZUNIONSTORE, CMD_ZSCAN,
	CMD_PUBLISH, CMD_SUBSCRIBE, CMD_UNSUBSCRIBE, CMD_PSUBSCRIBE, CMD_PUNSUBSCRIBE, CMD_PUBSUB,
	CMD_MULTI, CMD_EXEC, CMD_DISCARD, CMD_WATCH, CMD_UNWATCH, CMD_EVAL, CMD_EVALSHA, CMD_SCRIPT, CMD_LUA,
	CMD_GEOADD, CMD_GEODIST, CMD_GEOHASH, CMD_GEOPOS, CMD_GEORADIUS, CMD_GEORADIUSBYMEMBER,
	CMD_GEORADIUSBYLEX, CMD_GEOSEARCH, CMD_GEOSEARCHSTORE,
	CMD_PFADD, CMD_PFCOUNT, CMD_PFMERGE,
	CMD_XADD, CMD_XDEL, CMD_XTRIM, CMD_XCLAIM, CMD_XAUTOCLAIM, CMD_XGROUP, CMD_XINFO, CMD_XREAD,
	CMD_XREADGROUP, CMD_XACK, CMD_XPENDING, CMD_XRANGE, CMD_XREVRANGE, CMD_XSETID, CMD_XPOP,
	CMD_BITFIELD_RO, CMD_BITFIELD,
	CMD_STRALGO, CMD_SWAPDB, CMD_UNLINK, CMD_WAIT, CMD_REPLICAOF, CMD_REPLICA, CMD_PSYNC, CMD_LUA_RO,
	CMD_LUA_WRITE, CMD_HELLO,
}
